### ISSUE TITLE
Write triggering examples for devices that support triggering

### ISSUE THREAD

**Issue by ThorlabsMCalle** [Thorlabs/Motion_Control_Examples#21]

**Comment by BogdanL2022** [comment]
With the simulator you get an error in:
IOPortConfigParameters IOConfig = device.GetIOPortConfigParams(0x01);

An unhandled exception of type 'System.NullReferenceException' occurred in Thorlabs.MotionControl.DeviceManagerCLI.dll
Additional information: Object reference not set to an instance of an object.
