### ISSUE TITLE
kpz101_pythonnet

### ISSUE THREAD

**Issue by BDImagingLab** [Thorlabs/Motion_Control_Examples#24]
When using this code to control the KPZ101, it shows up an error message:
![image](https://user-images.githubusercontent.com/97756586/231346782-79fde854-ab22-4e26-9e34-64141207b851.png)
Meanwhile, I can connect and control the stage with Kinesis software. When running python, it is disconnected in Kinesis.
![image](https://user-images.githubusercontent.com/97756586/231346996-9cd5a9a4-4a7c-4e97-a621-8e21730254b0.png)

**Comment by BDImagingLab** [comment]
This is python code that I use.

import os
import time
import sys
import clr

clr.AddReference("C:\\Program Files\\Thorlabs\\Kinesis\\Thorlabs.MotionControl.DeviceManagerCLI.dll")
clr.AddReference("C:\\Program Files\\Thorlabs\\Kinesis\\Thorlabs.MotionControl.GenericMotorCLI.dll")
clr.AddReference("C:\\Program Files\\Thorlabs\\Kinesis\\ThorLabs.MotionControl.KCube.PiezoCLI.dll")
from Thorlabs.MotionControl.DeviceManagerCLI import *
from Thorlabs.MotionControl.GenericMotorCLI import *
from Thorlabs.MotionControl.KCube.PiezoCLI import *
from System import Decimal  # necessary for real world units

DeviceManagerCLI.BuildDeviceList()

# create new device
serial_no = "29501195"  # Replace this line with your device's serial number

# Connect, begin polling, and enable
device = KCubePiezo.CreateKCubePiezo(serial_no)

# Get Device Information and display description
device_info = device.GetDeviceInfo()
print(device_info.Description)

**Comment by iago-rst** [comment]
Hi!

Are you simulating the device or is it a physical one? At least to me, InitializeSimulations() only works when the Kinesis GUI is closed. Apparently the Kinesis server can only take up to one "pipe", so either Python is connected or the GUI is connected. You can see these log messages on the Kinesis Simlulator app.

Now, I am also running into an issue when calling TLI_GetHardwareInfo, which is similar to .NET GetDeviceInfo(). Whenever I run this function, my kernel crashes xD

Hope this gives you some more clue as to what might be wrong!

**Comment by TrumanMetz** [comment]
Hi,
Our apologies for the late response, but if you are still having issues with this error please reach out to our support team at [techsupport@thorlabs.com](https://www.thorlabs.com/locations.cfm) to speak with one of our engineers directly.
