### ISSUE TITLE
Examples for reading position? 

### ISSUE THREAD

**Issue by KardoPaska** [Thorlabs/Motion_Control_Examples#30]
This github repo is a great idea by Thorlabs management and is a great first step to addressing the severe lack of instructional examples.  

The entirely auto-generated .NET documentation makes the learning curve extremely steep for end users.  

It does not tell you that the `Position` property only updates at the polling cycle (which is often 250 ms or 500 ms in the examples).

It does not explain that the deceptively named function, `RequestPosition()`, does not actually request a new position -- it returns the stored `Position` from the last poll, which is likely wrong ... because ... it ... is ... moving ...

Calling `RequestStatus()` and reading the `.Status.Position` property will give a "live" position.  That took me lots of trial and error to figure out.  

Please keep improving and adding to this repo!  Thanks.

**Comment by manzelmi-thorlabs** [comment]
Hello and thank you for your comment! We appreciate the feedback and are in the process of creating some additional documentation on the Kinesis SDK, which will include a better explanation of the device polling loop and status updates. These documents will be added to this repository when ready. If you have any other suggestions for improvement or questions, please feel free to comment here or to email us at TechSupport@Thorlabs.com.

**Comment by KardoPaska** [comment]
Thanks for completing.

**Comment by KardoPaska** [comment]
@manzelmi-thorlabs Thanks for completing.
