### ISSUE TITLE
Kinesis software fails to list device channels after interfacing with CLI script.

### ISSUE THREAD

**Issue by Duxon** [Thorlabs/Motion_Control_Examples#32]
I had an issue with the `Thorlabs.MotionControl.DeviceManagerCLI` and standard Kinesis GUI. 

After connecting to a driver and failing (or forgetting) to stop polling and disconnecting with the CLI, there is a persistent bug in Kinesis: My BSC202 only shows one instead of two channels when connecting through the GUI.

Reinstalling, restarting, etc won't fix the issue. The only thing that helped was deleting the settings XML file of Kinesis located in
'C:\Users\[USERNAME]\AppData\Local\Thorlabs\Motion Control\Thorlabs.MotionControl.Kinesis'.
By doing so, a new one is created at the next startup of Kinesis, fixing the issue and again showing all channels.

**Comment by TrumanMetz** [comment]
Hi, 
Thank you for your feedback. We have seen this issue pop up a couple times and are working on fixing the issue. I'm glad you managed to get your controller working again but feel free to reach out to [techsupport@thorlabs.com](https://www.thorlabs.com/locations.cfm) if you have any other questions or concerns.
