### ISSUE TITLE
Issue with units for moves with rotation stage

### ISSUE THREAD

**Issue by manzelmi-thorlabs** [Thorlabs/Motion_Control_Examples#42]
I am using a BSC201 with an HDR50/M and want to set the velocity based on degrees per second rather than based on motor percentage. I tried using ```channel.SetVelocityParams_DeviceUnits()``` but I got an error that no attribute exist. Any help would be greatly appreciated!

_Originally posted by @camron-musashi in https://github.com/Thorlabs/Motion_Control_Examples/discussions/20#discussioncomment-8456292_

**Comment by Doneill-Thorlabs** [comment]
To set the velocity in real world units (in this case degrees per second) you would use SetVelocityParams(Decimal maxVelocity, Decimal acceleration) or SetVelocityParams(VelocityParameters ^ velocityParameters). 
If you have any further issues with this feel free to reach out to your local tech support
