### ISSUE TITLE
time.sleep(25) --> time.sleep(0.25)

### ISSUE THREAD

**Issue by cyamahat** [Thorlabs/Motion_Control_Examples#46]
[Motion_Control_Examples](https://github.com/Thorlabs/Motion_Control_Examples/tree/main)/[Python](https://github.com/Thorlabs/Motion_Control_Examples/tree/main/Python)/[KCube](https://github.com/Thorlabs/Motion_Control_Examples/tree/main/Python/KCube)/[KPZ101](https://github.com/Thorlabs/Motion_Control_Examples/tree/main/Python/KCube/KPZ101)
/kpz101_pythonnet.py

Script successfully tested. 

However, the initialisation takes quite a long time.
I figured out why: There is a **time.sleep(25)** [line 44] and I assume that it could be decreased to 0.25 (i.e., like at line 46).

**Comment by Doneill-Thorlabs** [comment]
Thank you for your comment. You are right that this is a typo. I will fix this and update this.

**Comment by bng919** [comment]
Same typo in [PFM450_pythonnet.py](https://github.com/Thorlabs/Motion_Control_Examples/blob/088a9dfc0d1ae5f3b8b51bb06ae230bc6445b0dc/Python/Benchtop/PPC00X/PFM450_pythonnet.py)

https://github.com/Thorlabs/Motion_Control_Examples/blob/088a9dfc0d1ae5f3b8b51bb06ae230bc6445b0dc/Python/Benchtop/PPC00X/PFM450_pythonnet.py#L60
