### ISSUE TITLE
bbd_pythonnet example error

### ISSUE THREAD

**Issue by Sibyl100** [Thorlabs/Motion_Control_Examples#52]
When I try to run the bbd_pythonnet.py example for the BBD30X Benchtop Controller line 59 raises the error "'Brushless30XMotorChannel' object has no attribute 'UpdateConfiguration'". When listing the methods of channel, defined on line 38, 'UpdateConfiguration' is not a method of this class.

**Comment by TrumanMetz** [comment]
Hello, thank you for bringing this to our attention. I believe this is a typo "UpdateConfiguration" should be "UpdateCurrentConfiguration" We'll have this fixed in the next pull request to the motion control repo.
