### ISSUE TITLE
Data integrity might be compromised from device

### ISSUE THREAD

**Issue by Rupayan3** [Thorlabs/Motion_Control_Examples#55]
We are Kinesis piezo motorized translation stage (PD-1/M) with controller (KIM 101) to change position of one our optical mounts. We are taking lot of data points for various positions of the translation stage. Some times the outputs prints the following message - 
"Data integrity might be compromised from device". Not understanding the issue. Any help in this regard is appreciated

**Comment by TrumanMetz** [comment]
Hello Rupayan, 
That error might be the result of the polling loop being too low. Kinesis by default polls most devices at 250ms. Most devices can go as low as 150ms but below this threshold the returns become unreliable. I hope this helps but feel free to contact your local tech support team (https://www.thorlabs.com/locations.cfm) if this doesn't solve the issue.
