### ISSUE TITLE
Using Piezo Translation stage - Device disconnected

### ISSUE THREAD

**Issue by Rupayan3** [Thorlabs/Motion_Control_Examples#56]
We are using Thorlabs piezo motorized translation stage. We are taking lot of data at various positions of the translation stage but sometimes output shows "device disconnected" due to which data is lost or corrupted as the program goes forward assuming it moved to the next position but in reality the translation stage is at the  previous position. What can be the reason of this disconnections?

**Comment by TrumanMetz** [comment]
Hello,
I'm sorry you are having issues with your piezo stage. I urge you to contact your local Tech Support team (https://www.thorlabs.com/locations.cfm) so we can help you troubleshoot this issue directly.
