### ISSUE TITLE
API documentation for the Kinesis commands 

### ISSUE THREAD

**Issue by mhturner** [Thorlabs/Motion_Control_Examples#61]
I'm using the Python example scripts for interacting with KCubes, and I'm having trouble adapting the code to my own purposes because I cannot seem to find documentation anywhere describing the functions, attributes, etc available in the Kinesis python packages. The dlls that are on my machine are compiled so I can't even look at the source code to understand how to interact with the python modules. Does this documentation exist somewhere?

**Comment by TrumanMetz** [comment]
Hello, 

Thank you for your inquiry. The class and method descriptions are housed in the .chm help files in your Kinesis install location (C:\Program Files\Thorlabs\Kinesis) named Thorlabs.MotionControl.C_API.chm (if you are using ctypes) and Thorlabs.MotionControl.DotNET_API.chm (if you are using pythonnet). I hope this helps but please feel free to message us at Techsupport@thorlabs.com if you have any questions regarding how specific commands work. 

- Truman Metz
